[
   JBCLimitStack            -- KW[".limit"] KW["stack"] _1,
   JBCLimitLocals           -- KW[".limit"] KW["locals"] _1,
   JBCLine                  -- KW[".line"] _1,
   JBCThrows                -- KW[".throws"] _1,
   JBCCatch                 -- KW[".catch"] _1 KW["from"] _2 KW["to"] _3 KW["using"] _4,
   JBCVarDecl               -- KW[".var"] _1 KW["is"] _2 _3 KW["from"] _4 KW["to"] _5,
   MONITORENTER             -- KW["monitorenter"],
   MONITOREXIT              -- KW["monitorexit"],
   ATHROW                   -- KW["athrow"],
   INVOKESPECIAL            -- KW["invokenonvirtual"] _1,
   INVOKEVIRTUAL            -- KW["invokevirtual"] _1,
   INVOKESTATIC             -- KW["invokestatic"] _1,
   INVOKEINTERFACE          -- KW["invokeinterface"] _1 _2,
   RETURN                   -- KW["return"],
   IRETURN                  -- KW["ireturn"],
   LRETURN                  -- KW["lreturn"],
   FRETURN                  -- KW["freturn"],
   DRETURN                  -- KW["dreturn"],
   ARETURN                  -- KW["areturn"],
   Absolute                 -- _1,
   RelativeFwd              -- KW["$+"] _1,
   RelativeBwd              -- KW["$-"] _1,
   IFEQ                     -- KW["ifeq"] _1,
   IFLT                     -- KW["iflt"] _1,
   IFLE                     -- KW["ifle"] _1,
   IFNE                     -- KW["ifne"] _1,
   IFGT                     -- KW["ifgt"] _1,
   IFGE                     -- KW["ifge"] _1,
   IFNULL                   -- KW["ifnull"] _1,
   IFNONNULL                -- KW["ifnonnull"] _1,
   IF_ICMPEQ                -- KW["if_icmpeq"] _1,
   IF_ICMPLT                -- KW["if_icmplt"] _1,
   IF_ICMPLE                -- KW["if_icmple"] _1,
   IF_ICMPNE                -- KW["if_icmpne"] _1,
   IF_ICMPGT                -- KW["if_icmpgt"] _1,
   IF_ICMPGE                -- KW["if_icmpge"] _1,
   IF_ACMPEQ                -- KW["if_acmpeq"] _1,
   IF_ACMPNE                -- KW["if_acmpne"] _1,
   Table                    -- KW["tableswitch"] _1 _2 KW["default"] KW[":"] _3,
   Table.2:iter-star        -- _1,
   Lookup                   -- KW["lookupswitch"] _1 KW["default"] KW[":"] _2,
   Lookup.1:iter-star       -- _1,
   Jump                     -- _1,
   NPAIR                    -- _1 KW[":"] _2,
   GOTO                     -- KW["goto"] _1,
   GOTO_W                   -- KW["goto_w"] _1,
   POP                      -- KW["pop"],
   POP2                     -- KW["pop2"],
   DUP                      -- KW["dup"],
   DUP2                     -- KW["dup2"],
   DUP_X1                   -- KW["dup_x1"],
   DUP2_X1                  -- KW["dup2_x1"],
   DUP_X2                   -- KW["dup_x2"],
   DUP2_X2                  -- KW["dup2_x2"],
   SWAP                     -- KW["swap"],
   NEW                      -- KW["new"] _1,
   NEWARRAY                 -- KW["newarray"] _1,
   ANEWARRAY                -- KW["anewarray"] _1,
   ANEWARRAY                -- KW["anewarray"] _1,
   MULTIANEWARRAY           -- KW["multianewarray"] _1 _2,
   GETFIELD                 -- KW["getfield"] _1,
   PUTFIELD                 -- KW["putfield"] _1,
   GETSTATIC                -- KW["getstatic"] _1,
   PUTSTATIC                -- KW["putstatic"] _1,
   IALOAD                   -- KW["iaload"],
   LALOAD                   -- KW["laload"],
   BALOAD                   -- KW["baload"],
   CALOAD                   -- KW["caload"],
   SALOAD                   -- KW["saload"],
   FALOAD                   -- KW["faload"],
   DALOAD                   -- KW["daload"],
   AALOAD                   -- KW["aaload"],
   IASTORE                  -- KW["iastore"],
   LASTORE                  -- KW["lastore"],
   BASTORE                  -- KW["bastore"],
   CASTORE                  -- KW["castore"],
   SASTORE                  -- KW["sastore"],
   FASTORE                  -- KW["fastore"],
   DASTORE                  -- KW["dastore"],
   AASTORE                  -- KW["aastore"],
   ARRAYLENGTH              -- KW["arraylength"],
   CHECKCAST                -- KW["checkcast"] _1,
   INSTANCEOF               -- KW["instanceof"] _1,
   I2L                      -- KW["i2l"],
   I2F                      -- KW["i2f"],
   I2D                      -- KW["i2d"],
   L2F                      -- KW["l2f"],
   L2D                      -- KW["l2d"],
   F2D                      -- KW["f2d"],
   I2B                      -- KW["int2byte"],
   I2S                      -- KW["int2short"],
   I2C                      -- KW["int2char"],
   L2I                      -- KW["l2i"],
   F2I                      -- KW["f2i"],
   F2L                      -- KW["f2l"],
   D2I                      -- KW["d2i"],
   D2L                      -- KW["d2l"],
   D2F                      -- KW["d2f"],
   IADD                     -- KW["iadd"],
   IAND                     -- KW["iand"],
   IDIV                     -- KW["idiv"],
   IMUL                     -- KW["imul"],
   INEG                     -- KW["ineg"],
   IOR                      -- KW["ior"],
   IREM                     -- KW["irem"],
   ISHL                     -- KW["ishl"],
   ISHR                     -- KW["ishr"],
   ISUB                     -- KW["isub"],
   IUSHR                    -- KW["iushr"],
   IXOR                     -- KW["ixor"],
   LADD                     -- KW["ladd"],
   LAND                     -- KW["land"],
   LDIV                     -- KW["ldiv"],
   LMUL                     -- KW["lmul"],
   LNEG                     -- KW["lneg"],
   LOR                      -- KW["lor"],
   LREM                     -- KW["lrem"],
   LSHL                     -- KW["lshl"],
   LSHR                     -- KW["lshr"],
   LSUB                     -- KW["lsub"],
   LUSHR                    -- KW["lushr"],
   LXOR                     -- KW["lxor"],
   FADD                     -- KW["fadd"],
   FDIV                     -- KW["fdiv"],
   FMUL                     -- KW["fmul"],
   FNEG                     -- KW["fneg"],
   FREM                     -- KW["frem"],
   FSUB                     -- KW["fsub"],
   DADD                     -- KW["dadd"],
   DDIV                     -- KW["ddiv"],
   DMUL                     -- KW["dmul"],
   DNEG                     -- KW["dneg"],
   DREM                     -- KW["drem"],
   DSUB                     -- KW["dsub"],
   IINC                     -- KW["iinc"] _1 _2,
   Neg                      -- KW["-"] _1,
   FCMPG                    -- KW["fcmpg"],
   FCMPL                    -- KW["fcmpl"],
   DCMPG                    -- KW["dcmpg"],
   DCMPL                    -- KW["dcmpl"],
   LCMP                     -- KW["lcmp"],
   BIPUSH                   -- KW["bipush"] _1,
   SIPUSH                   -- KW["sipush"] _1,
   ICONST_M1                -- KW["iconst_m1"],
   ICONST_0                 -- KW["iconst_0"],
   ICONST_1                 -- KW["iconst_1"],
   ICONST_2                 -- KW["iconst_2"],
   ICONST_3                 -- KW["iconst_3"],
   ICONST_4                 -- KW["iconst_4"],
   ICONST_5                 -- KW["iconst_5"],
   LCONST_0                 -- KW["lconst_0"],
   LCONST_1                 -- KW["lconst_1"],
   FCONST_0                 -- KW["fconst_0"],
   FCONST_1                 -- KW["fconst_1"],
   FCONST_2                 -- KW["fconst_2"],
   DCONST_0                 -- KW["dconst_0"],
   DCONST_1                 -- KW["dconst_1"],
   ACONST_NULL              -- KW["aconst_null"],
   LDC                      -- KW["ldc"] _1,
   LDC2_W                   -- KW["ldc2_w"] _1,
   ILOAD                    -- KW["iload"] _1,
   LLOAD                    -- KW["lload"] _1,
   FLOAD                    -- KW["fload"] _1,
   DLOAD                    -- KW["dload"] _1,
   ALOAD                    -- KW["aload"] _1,
   ILOAD_0                  -- KW["iload_0"],
   ILOAD_1                  -- KW["iload_1"],
   ILOAD_2                  -- KW["iload_2"],
   ILOAD_3                  -- KW["iload_3"],
   ALOAD_0                  -- KW["aload_0"],
   ALOAD_1                  -- KW["aload_1"],
   ALOAD_2                  -- KW["aload_2"],
   ALOAD_3                  -- KW["aload_3"],
   LLOAD_0                  -- KW["lload_0"],
   LLOAD_1                  -- KW["lload_1"],
   LLOAD_2                  -- KW["lload_2"],
   LLOAD_3                  -- KW["lload_3"],
   DLOAD_0                  -- KW["dload_0"],
   DLOAD_1                  -- KW["dload_1"],
   DLOAD_2                  -- KW["dload_2"],
   DLOAD_3                  -- KW["dload_3"],
   FLOAD_0                  -- KW["fload_0"],
   FLOAD_1                  -- KW["fload_1"],
   FLOAD_2                  -- KW["fload_2"],
   FLOAD_3                  -- KW["fload_3"],
   ISTORE                   -- KW["istore"] _1,
   LSTORE                   -- KW["lstore"] _1,
   FSTORE                   -- KW["fstore"] _1,
   DSTORE                   -- KW["dstore"] _1,
   ASTORE                   -- KW["astore"] _1,
   ISTORE_0                 -- KW["istore_0"],
   ISTORE_1                 -- KW["istore_1"],
   ISTORE_2                 -- KW["istore_2"],
   ISTORE_3                 -- KW["istore_3"],
   ASTORE_0                 -- KW["astore_0"],
   ASTORE_1                 -- KW["astore_1"],
   ASTORE_2                 -- KW["astore_2"],
   ASTORE_3                 -- KW["astore_3"],
   LSTORE_0                 -- KW["lstore_0"],
   LSTORE_1                 -- KW["lstore_1"],
   LSTORE_2                 -- KW["lstore_2"],
   LSTORE_3                 -- KW["lstore_3"],
   FSTORE_0                 -- KW["fstore_0"],
   FSTORE_1                 -- KW["fstore_1"],
   FSTORE_2                 -- KW["fstore_2"],
   FSTORE_3                 -- KW["fstore_3"],
   DSTORE_0                 -- KW["dstore_0"],
   DSTORE_1                 -- KW["dstore_1"],
   DSTORE_2                 -- KW["dstore_2"],
   DSTORE_3                 -- KW["dstore_3"],
   NOP                      -- KW["nop"],
   BREAKPOINT               -- KW["breakpoint"],
   PC                       -- _1 KW[":"] _2,
   JBCMethod                -- KW[".method"] _1 _2 _3 _4 KW[".end"] KW["method"],
   JBCMethod.1:iter-star    -- _1,
   JBCMethod.4:iter-star    -- _1,
   PUBLIC                   -- KW["public"],
   PRIVATE                  -- KW["private"],
   PROTECTED                -- KW["protected"],
   STATIC                   -- KW["static"],
   FINAL                    -- KW["final"],
   SYNCHRONIZED             -- KW["synchronized"],
   NATIVE                   -- KW["native"],
   ABSTRACT                 -- KW["abstract"],
   JBCLabel                 -- _1 KW[":"],
   JBCField                 -- KW[".field"] _1 _2 _3 _4 _5,
   JBCField.1:iter-star     -- _1,
   JBCExtField              -- KW[".field"] _1 _2 _3 _4 _5 KW[".end"] KW["field"],
   JBCExtField.1:iter-star  -- _1,
   JBCExtField.5:iter-star  -- _1,
   JBCSignature             -- KW[".signature"] _1,
   JBCDeprecated            -- KW[".deprecated"],
   FieldSig                 -- KW["signature"] _1,
   None                     -- ,
   InitVal                  -- KW["="] _1,
   None                     -- ,
   PUBLIC                   -- KW["public"],
   PRIVATE                  -- KW["private"],
   PROTECTED                -- KW["protected"],
   STATIC                   -- KW["static"],
   FINAL                    -- KW["final"],
   VOLATILE                 -- KW["volatile"],
   TRANSIENT                -- KW["transient"],
   JBCFieldDesc             -- _1,
   Void                     -- KW["V"],
   Byte                     -- KW["B"],
   Char                     -- KW["C"],
   Double                   -- KW["D"],
   Float                    -- KW["F"],
   Int                      -- KW["I"],
   Long                     -- KW["J"],
   Short                    -- KW["S"],
   Boolean                  -- KW["Z"],
   Init                     -- KW["<init>"],
   CRef                     -- _1,
   VarNum                   -- _1,
   LabelRef                 -- _1,
   FRef                     -- _1,
   MRef                     -- _1,
   ByteName                 -- KW["byte"],
   CharName                 -- KW["char"],
   DoubleName               -- KW["double"],
   FloatName                -- KW["float"],
   IntName                  -- KW["int"],
   LongName                 -- KW["long"],
   ShortName                -- KW["short"],
   BooleanName              -- KW["boolean"],
   JBCHeader                -- _1 _2 _3 _4 _5 _6 _7 _8,
   JBCHeader.5:iter-star    -- _1,
   JBCVersion               -- KW[".bytecode"] _1 _2,
   None                     -- ,
   Major                    -- _1,
   Minor                    -- KW["."] _1,
   None                     -- ,
   JBCSource                -- KW[".source"] _1,
   None                     -- ,
   JBCClass                 -- V  [V vs=2 [KW[".class"] _1] _2],
   JBCClass.1:iter-star     -- _1,
   JBCInterface             -- V  [V vs=2 [KW[".interface"] _1] _2],
   JBCInterface.1:iter-star -- _1,
   PUBLIC                   -- KW["public"],
   FINAL                    -- KW["final"],
   INTERFACE                -- KW["interface"],
   ABSTRACT                 -- KW["abstract"],
   SUPER                    -- KW["super"],
   JBCSuper                 -- KW[".super"] _1,
   JBCImplements            -- KW[".implements"] _1,
   JBCSignature             -- KW[".signature"] _1,
   None                     -- ,
   JBCEnclosing             -- KW[".enclosing"] KW["method"] _1,
   None                     -- ,
   JBCDeprecated            -- KW[".deprecated"],
   None                     -- ,
   JBCFile                  -- _1 _2 _3,
   JBCFile.2:iter-star      -- _1,
   JBCFile.3:iter-star      -- _1
]