[
   JBCLimitStack             -- H [KW[".limit"] KW["stack"] _1],
   JBCLimitLocals            -- H [KW[".limit"] KW["locals"] _1],
   JBCLine                   -- H [KW[".line"] _1],
   JBCThrows                 -- H [KW[".throws"] _1],
   JBCCatch                  -- H [KW[".catch"] _1 KW["from"] _2 KW["to"] _3 KW["using"] _4],
   JBCVarDecl                -- H [KW[".var"] _1 KW["is"] _2 _3 KW["from"] _4 KW["to"] _5],
   INVOKESPECIAL             -- H [KW["invokenonvirtual"] _1],
   INVOKEVIRTUAL             -- H [KW["invokevirtual"] _1],
   INVOKESTATIC              -- H [KW["invokestatic"] _1],
   INVOKEINTERFACE           -- H [KW["invokeinterface"] _1 _2],
   RelativeFwd               -- H [KW["$+"] _1],
   RelativeBwd               -- H [KW["$-"] _1],
   IFEQ                      -- H [KW["ifeq"] _1],
   IFLT                      -- H [KW["iflt"] _1],
   IFLE                      -- H [KW["ifle"] _1],
   IFNE                      -- H [KW["ifne"] _1],
   IFGT                      -- H [KW["ifgt"] _1],
   IFGE                      -- H [KW["ifge"] _1],
   IFNULL                    -- H [KW["ifnull"] _1],
   IFNONNULL                 -- H [KW["ifnonnull"] _1],
   IF_ICMPEQ                 -- H [KW["if_icmpeq"] _1],
   IF_ICMPLT                 -- H [KW["if_icmplt"] _1],
   IF_ICMPLE                 -- H [KW["if_icmple"] _1],
   IF_ICMPNE                 -- H [KW["if_icmpne"] _1],
   IF_ICMPGT                 -- H [KW["if_icmpgt"] _1],
   IF_ICMPGE                 -- H [KW["if_icmpge"] _1],
   IF_ACMPEQ                 -- H [KW["if_acmpeq"] _1],
   IF_ACMPNE                 -- H [KW["if_acmpne"] _1],
   Table                     -- H [KW["tableswitch"] _1 _2 KW["default"] KW[":"] _3],
   Lookup                    -- H [KW["lookupswitch"] _1 KW["default"] KW[":"] _2],
   NPAIR                     -- H [_1 KW[":"] _2],
   GOTO                      -- H [KW["goto"] _1],
   GOTO_W                    -- H [KW["goto_w"] _1],
   NEW                       -- H [KW["new"] _1],
   NEWARRAY                  -- H [KW["newarray"] _1],
   ANEWARRAY                 -- H [KW["anewarray"] _1],
   ANEWARRAY                 -- H [KW["anewarray"] _1],
   MULTIANEWARRAY            -- H [KW["multianewarray"] _1 _2],
   GETFIELD                  -- H [KW["getfield"] _1],
   PUTFIELD                  -- H [KW["putfield"] _1],
   GETSTATIC                 -- H [KW["getstatic"] _1],
   PUTSTATIC                 -- H [KW["putstatic"] _1],
   CHECKCAST                 -- H [KW["checkcast"] _1],
   INSTANCEOF                -- H [KW["instanceof"] _1],
   IINC                      -- H [KW["iinc"] _1 _2],
   Neg                       -- H [KW["-"] _1],
   BIPUSH                    -- H [KW["bipush"] _1],
   SIPUSH                    -- H [KW["sipush"] _1],
   LDC                       -- H [KW["ldc"] _1],
   LDC2_W                    -- H [KW["ldc2_w"] _1],
   ILOAD                     -- H [KW["iload"] _1],
   LLOAD                     -- H [KW["lload"] _1],
   FLOAD                     -- H [KW["fload"] _1],
   DLOAD                     -- H [KW["dload"] _1],
   ALOAD                     -- H [KW["aload"] _1],
   ISTORE                    -- H [KW["istore"] _1],
   LSTORE                    -- H [KW["lstore"] _1],
   FSTORE                    -- H [KW["fstore"] _1],
   DSTORE                    -- H [KW["dstore"] _1],
   ASTORE                    -- H [KW["astore"] _1],
   PC                        -- H [_1 KW[":"] _2],
   JBCMethod                 -- V [V is=4[H [KW[".method"] _1 H hs=0 [_2 _3]] _4] H [KW[".end"] KW["method"]]],
   JBCLabel                  -- H [_1 KW[":"]],
   JBCField                  -- H [KW[".field"] _1 _2 _3 _4 _5],
   JBCExtField               -- KW[".field"] _1 _2 _3 _4 _5 KW[".end"] KW["field"],
   JBCSignature              -- H [KW[".signature"] _1],
   FieldSig                  -- H [KW["signature"] _1],
   JBCMethodDesc             -- H hs=0 [KW["("] _1 KW[")"] _2],
   JBCMethodDesc.1:iter-star -- _1,
   Reference                 -- H hs=0[KW["L"] _1 KW[";"]],
   Array                     -- H hs=0[KW["["] _1],
   JBCFieldRef               -- H [H hs=0 [_1 KW["/"] _2] _3],
   JBCMethodRef              -- H hs=0[_1 KW["/"] _2 _3],
   JBCHeader                 -- V vs=0[_1 _2 _3 _4 _5 _6 _7 _8],
   JBCVersion                -- H [KW[".bytecode"] _1 _2],
   JBCSource                 -- H [KW[".source"] _1],
   JBCClass                  -- H  [H hs=1 [KW[".class"] _1] _2],
   JBCInterface              -- V  [V vs=2 [KW[".interface"] _1] _2],
   JBCSuper                  -- H [KW[".super"] _1],
   JBCImplements             -- H [KW[".implements"] _1],
   JBCSignature              -- H [KW[".signature"] _1],
   JBCEnclosing              -- H [KW[".enclosing"] KW["method"] _1],
   JBCFile                   -- V vs=1[_1 _2 _3]
]